#########################################################################

#

pathInfo:
  inputDir: "/media/eva/DATA2/drMD_devel/drMD/cc_di/"
  outputDir: "/media/eva/DATA2/drMD_devel/drMD/cc_di/output/"
  
########################################################################
hardwareInfo:
  parallelCPU: 1
  platform: "CUDA"
  subprocessCpus: 1
########################################################################
miscInfo:
  pH: 7.4
  firstAidMaxRetries: 10
  boxGeometry: "cubic"
  writeMyMethodsSection: True
  skipPdbTriage: True
  trajectorySelections:
  - selection:
      keyword: "protein"
  - selection:
      keyword: "ligand"

########################################################################
equilibriationRestraints: &equilibriationRestraints
    - restraintType: "position"
      parameters:
        k: 1000
      selection:
        keyword: "protein"

    - restraintType: "position"
      selection: 
        keyword: "ligand"  
      parameters:
        k: 1000

########################################################################
simulationInfo:
  - stepName: "01_energy_minimisation"
    simulationType: "EM"
    temperature: 300
    maxIterations: -1
########################################################################
  - stepName: "02_NVT_pre-equilibriation"
    simulationType: "NVT"
    duration: "100 ps"
    timestep: "4 fs"
    heavyProtons: True
    temperature: 300
    logInterval: "1 ps"
    restraintInfo: *equilibriationRestraints

#########################################################################
  - stepName: "03_NPT_pre-equilibriation"
    simulationType: "NPT"
    duration: "100 ps"
    timestep: "4 fs"
    heavyProtons: True
    temperature: 300
    logInterval: "1 ps"
    restraintInfo: *equilibriationRestraints

########################################################################
  - stepName: "04_NpT_slowIntergrator"
    simulationType: "NpT"
    duration: "10 ps"
    timestep: "0.5 fs"
    temperature: 300
    logInterval: "1 ps"
########################################################################
  - stepName: "05_Equilibriation"
    simulationType: "NpT"
    duration: "5 ns"
    timestep: "4 fs"
    heavyProtons: True
    temperature: 300
    logInterval: "500 ps"

########################################################################
  - stepName: "06_Production_MD"
    simulationType: "NpT"
    duration: "10 ns"
    timestep: "4 fs"
    heavyProtons: True
    temperature: 300
    logInterval: "50 ps"
################################################
aftercareInfo:
  clusterInfo:
    stepNames: ["06_Production_MD"] 
    nClusters: 25
    clusterBy:
    - selection:
        keyword: "protein"
    removeAtoms:
      - selection:
          keyword: "water"
      - selection:
          keyword: "ions"
  collateVitalsReports: True

